#!/bin/bash
##run from results directory
##Output BED file is sorted for indexing and loading into IGV
##awk for converting SJ.out.tab to bed12 format
##based on code originally published by frymor at http://seqanswers.com/forums/showthread.php?t=62896
if [ "$1" == "-h" ]; then
  echo "Usage: `basename $0`  <FileIn.SJ.out.tab> <FileOut.junctions.bed>"
  echo ""
  echo "Takes a stranded SJ.out.tab file of introns generated by STAR aligner, with the number of junction reads in column7, and outputs a bed track like the one output by TopHat for viewing in IGV. Lighter RGB color codes used for junctions that are in SJ.out.tab but with 0 unique mapping read counts"
  exit 0
fi

sj=$1
junctions=$2

echo ${sj}
echo "Converting..."
awk \
{' \
if($4=="2" && $7>0) print ""$1"\t"$2-$9-1"\t"$3+$9"\tJUNC_"$1"_"$2"_"$3"_-\t"$7"\t-\t"$2-$9-1"\t"$3+$9"\t255,0,0\t2\t"$9","$9"\t","0,"$3-$2+$9+1; \
else \
if($4=="2" && $7==0) print ""$1"\t"$2-$9-1"\t"$3+$9"\tJUNC_"$1"_"$2"_"$3"_-\t"$7"\t-\t"$2-$9-1"\t"$3+$9"\t255,204,204\t2\t"$9","$9"\t","0,"$3-$2+$9+1; \
else \
if($4=="1" && $7>0) print ""$1"\t"$2-$9-1"\t"$3+$9"\tJUNC_"$1"_"$2"_"$3"_+\t"$7"\t+\t"$2-$9-1"\t"$3+$9"\t0,0,255\t2\t"$9","$9"\t","0,"$3-$2+$9+1; \
else \
if($4=="1" && $7==0) print ""$1"\t"$2-$9-1"\t"$3+$9"\tJUNC_"$1"_"$2"_"$3"_+\t"$7"\t+\t"$2-$9-1"\t"$3+$9"\t204,204,255\t2\t"$9","$9"\t","0,"$3-$2+$9+1'} \
${sj} | sort -k 1,1 -k2,2n | awk 'BEGIN{print "track name=junctions description=\47TopHat junctions\47"} {print}' > $junctions
echo "Complete"
